apiVersion: v1
kind: Service
metadata:
  name: "mcp-client"
  labels:
    network-pool: {{ .Values.service.networkPool }}
    {{- include "mcp-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
