apiVersion: v2
name: mcp-client
description: A Helm chart for deploying the MCP Client application with PostgreSQL database, authentication, and user management
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - mcp
  - client
  - postgresql
  - authentication
  - api
home: https://github.com/GalShafir/nova-nexus-engine
sources:
  - https://github.com/GalShafir/nova-nexus-engine
maintainers:
  - name: MCP Client Team
    email: admin@mcp-client.local
annotations:
  category: Application
