# Production values for mcp-client
# Use this file for production: helm install mcp-client ./charts/mcp-client -f values-prod.yaml

# Production image settings
image:
  repository: your-registry.com/mcp-client
  tag: "1.0.0"
  pullPolicy: IfNotPresent

# Production replicas for high availability
replicaCount: 3

# Production environment variables
env:
  LOG_LEVEL: "WARNING"
  LLM_SSL_VERIFY: "true"
  # Set these via secrets in production:
  # LLM_API_KEY: ""
  # DATABASE_PASSWORD: ""

# Production resource allocation
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

# PostgreSQL production settings
postgres:
  # Set this via secret in production
  password: "CHANGE_THIS_IN_PRODUCTION_VIA_SECRET"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    size: 50Gi
    storageClass: "fast-ssd"  # Use your production storage class

# Production security
auth:
  jwtSecret: "CHANGE_THIS_IN_PRODUCTION_VIA_SECRET"
  accessTokenExpire: 1800  # 30 minutes for production
  admin:
    password: "CHANGE_THIS_IMMEDIATELY"

# Production features
features:
  enableUserRegistration: false  # Disable for production
  enableGuestAccess: false
  enableMetrics: true
  enableTracing: true

# Production ingress with TLS
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: mcp-client.your-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: mcp-client-tls
      hosts:
        - mcp-client.your-domain.com

# Autoscaling for production load
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Production affinity (spread across nodes)
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - mcp-client
        topologyKey: kubernetes.io/hostname

# External services for production
external:
  redis:
    enabled: true
    host: "redis.your-domain.com"
    port: 6379
    database: 0
  
  prometheus:
    enabled: true
    port: 9090
    path: /metrics

# Production tolerations
tolerations:
  - key: "production"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
